name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Download WebRTC
      run: mkdir libs && wget -O libs/libwebrtc-m99.aar https://gultsch.de/files/libwebrtc-m99.aar
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Quicksy
      run: ./gradlew assembleQuicksyFreeDebug
    - name: Build Conversations
      run: ./gradlew assembleConversationsFreeDebug
    - uses: actions/upload-artifact@v2
      with:
        name: Conversations all-flavors (debug)
        path: ./build/outputs/apk/**/debug/Conversations-*.apk

      
